name = "battlesnake"
type = "javascript"
account_id = "fb1f542488f2441acf88ca15f3a8390d"
workers_dev = true
compatibility_date = "2022-01-15"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
